### ISSUE TITLE
Science Carnival Abstract

### ISSUE THREAD

**Issue by HocketPulk** [HocketPulk/Spring-Quater#5]

**Comment by scosha20** [comment]
[A&C S17 Science Carnival Abstract.docx](https://github.com/HocketPulk/Spring-Quater/files/988687/A.C.S17.Science.Carnival.Abstract.docx)


 let me know what yall think, ill share to canvas before class tomorrow if its a go.

**Comment by scosha20** [comment]
Abstract: What are gravitational waves? How are they made and can we measure them? Through science and story our team will answer these questions by exploring themes that motivate their discovery. We will use the language of numbers and statistics to discuss what celestial conditions that create them. We will share how Physicists at the Laser Interferometer Gravitational-Wave Observatory (LIGO) in Hanford Washington are making ground breaking discovers while detecting cosmic gravitational waves. By using physical models and devices to demonstrate how gravitational waves effect the fabric of space we will be able to create an interactive experience all while explaining, Einstein’s Theory of General Relativity. And finally, we will discuss what this means to us and how gravitational waves effect systems here on Earth.

**Comment by HocketPulk** [comment]
➤ Shannon Scott commented:

I sent you an updated absract via email. Combining the two abstracts and reconfiguring them so that they fit within the perimeters of the assignment

**Comment by HocketPulk** [comment]
➤ Francisco Velez commented:

@shannonscott18 It looks really good! Thank you :)
